name: Build Application

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pyinstaller
    - name: Build executable for Windows
      run: |
        pyinstaller --onefile --add-data "flower_template_1.png;." --add-data "flower_template_2.png;." --add-data "flower_template_3.png;." --add-data "flower_template_4.png;." --add-data "flower_template_5.png;." --add-data "flower_template_6.png;." --add-data "ice_template_1.png;." --add-data "ice_template_2.png;." --add-data "ice_template_3.png;." --add-data "bomb_template_1.png;." --add-data "bomb_template_2.png;." --add-data "bomb_template_3.png;." --add-data "play_button_template.png;." --add-data "home.png;." --add-data "play_home.png;." main.py
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pyinstaller
    - name: Build executable for macOS
      run: |
        pyinstaller --onefile --add-data "flower_template_1.png:." --add-data "flower_template_2.png:." --add-data "flower_template_3.png:." --add-data "flower_template_4.png:." --add-data "flower_template_5.png:." --add-data "flower_template_6.png:." --add-data "ice_template_1.png:." --add-data "ice_template_2.png:." --add-data "ice_template_3.png:." --add-data "bomb_template_1.png:." --add-data "bomb_template_2.png:." --add-data "bomb_template_3.png:." --add-data "play_button_template.png:." --add-data "home.png:." --add-data "play_home.png:." main.py
    - name: Upload macOS executable
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: dist/main.app
